sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: u2zx4jIl+L6jOn91nVo04k1/ksggQDvhR+0VS7r1Y9vpwKNSOTc0zkk7x5sIzJWqrJMxod51z1rMrc8rJWOF3qV6DpONuGAuRW5PO3W7n56zf5pi3CHxGsNacA7vsgxs40pxEh1FHDQUOCCv1UEFbRmMRLV70gWpliUcD2yRXudDLf6xpHzr8Llj9FozxZcrPnXRQ8Ymr1l5yTPxYwXAL4TP51b1nYQhglTs8yWS/F3wi0Y1V/OJtRV9vuejQZY5PMpM/SlNxq0Lklk6H+bwuOsmUXBl3Amp/GBVXnugpuOtV2h9vgPDF8pI47e5ahaPDidOz5MSZ59FBc+IRp7H3VSMCf/9k/vNLKJScaBnHPaxajahjoE10U15b5P3WPlNDcAKN/5jG2XJt/i/SI6tf9dQc7UHyLvn+pjHGTeejxiHM/dT1lDE1cRS32wb1PyqP6pNyIecKDpFerpsZX1Q1ACABXWTyAIL/qv8qmSGRG1Bv6soxWhQBBbmwcrn2JjkgG6Q9EJCC0VA4dlpfSP4K3U+WH8l7YOLZ3HISAXdra1B800urVy0YlqRTawwEXXCktOO7ryjUplPAgsE9xed/LHIk22Tq79Nv3GU9FA3F0dg1jHlZLFqu0QWyqqas147QW9V3A3aaD6eNKXwMbJSD6CDfKM8d7wPlLH0ry+Q+EI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Potato-Child--amp--Others_5662
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy